### ISSUE TITLE
PAYMENTS: Support Stripe/paygates with overlay

### ISSUE THREAD

**Issue by ichpen** [gfnlabs/classifieds#13]
Currently Stripe payments part of bd gateway only work if you disable the overlay trigger in classifieds_item_view_sidebar template. Would be nice to have this work in the overlay if possible.

**Comment by sikhlana** [comment]
Unfortunately, this part is handled by [bd] Paygates and would be tough for me to do a bug fix for this as the form generated by the gateway is handled differently than XenForo's default way.

I'll see what I can do.

**Comment by ichpen** [comment]
Thanks. If you can't fix it properly at least do a template edit for those of us running Stripe in addition to Paypal so we don't overwrite our templates with each upgrade and break stripe.

Paypal works ok in the overlay.

**Comment by sikhlana** [comment]
That's a really good work-around.

**Comment by sikhlana** [comment]
A partial fix has been added where the admin can disable the overlay trigger by enabling the *__classifieds_item_view_sidebar__* template modification from AdminCP.
