### ISSUE TITLE
Addon Conflicts

### ISSUE THREAD

**Issue by BigIron5** [gfnlabs/classifieds#30]
Received this error after updating and attempting to visit with a user who has existing classified ads: 

`An exception occurred: Call to undefined function dump() in /home/nginx/domains/domainname.com/public/xenforo/library/GFNClassifieds/Model/Classified.php on line 1155

    GFNClassifieds_Model_Classified->canBumpClassified() in GFNClassifieds/Model/Classified.php at line 1575
    GFNClassifieds_Model_Classified->prepareClassified() in GFNClassifieds/Extend/XenForo/ControllerPublic/Forum.php at line 214
    GFNClassifieds_Extend_XenForo_ControllerPublic_Forum->_getClassifieds() in GFNClassifieds/Extend/XenForo/ControllerPublic/Forum.php at line 89
    GFNClassifieds_Extend_XenForo_ControllerPublic_Forum->actionIndex() in AttachStats/ControllerPublic/Forum.php at line 7
    AttachStats_ControllerPublic_Forum->actionIndex() in NFLJ/Showcase/XenForo/ControllerPublic/Forum.php at line 7
    NFLJ_Showcase_XenForo_ControllerPublic_Forum->actionIndex() in FS/Events/ControllerPublic/Forum.php at line 5
    FS_Events_ControllerPublic_Forum->actionIndex() in XenForo/FrontController.php at line 351
    XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 134
    XenForo_FrontController->run() in /home/nginx/domains/domainname.com/public/xenforo/index.php at line 13
`

**Comment by sikhlana** [comment]
This has been fixed.
