### ISSUE TITLE
AD STATES: Users are unable to re-open closed ads

### ISSUE THREAD

**Issue by BigIron5** [gfnlabs/classifieds#5]
When a user closes their ad they're instructed that they 'may not be able to open it again'. I don't see a permission for this and normal users are not able to re-open their closed ads. If I assign them the classified moderator permission "open/close classifieds by anyone" then they can open and close their ads.

**Comment by sikhlana** [comment]
That shouldn't be the case... I'll look into it.

**Comment by sikhlana** [comment]
This issue has been fixed.
